"use strict";

// Contenido real del sitio: guías de compra y artículos de blog.
// Nada de datos de producto inventados (ni precios exactos, ni valoraciones,
// ni modelos): son guías de criterio, no fichas de producto. Cuando haya tag
// de afiliado (ver PENDIENTE.md) cada guía enlazará productos concretos.

const GUIDES = [
  {
    slug: "sillas-ergonomicas",
    title: "Cómo elegir una silla ergonómica para el escritorio",
    dek: "Qué mirar de verdad antes de comprar: regulaciones, apoyo lumbar, malla o tapizado y cuándo compensa pagar más.",
    updated: "2026-09-15",
    img: "/assets/img/guias/sillas-ergonomicas.jpg",
    intro: [
      "Una silla mala no se nota el primer día: se nota a la tercera semana, cuando empieza el dolor lumbar o de cervicales. Es probablemente la pieza del escritorio donde más merece la pena mirar bien antes de comprar, porque un error aquí se paga en horas de espalda, no solo en dinero.",
      "Esta guía no recomienda un modelo concreto: te da los criterios para que compares cualquier silla con cabeza, incluidas las que encuentres en Amazon.",
    ],
    sections: [
      {
        heading: "Las regulaciones que de verdad importan",
        body: [
          "Altura del asiento: tiene que bajar lo suficiente para que tus pies apoyen en el suelo con las rodillas a 90°. Si tu mesa es fija y baja, esto manda sobre todo lo demás.",
          "Profundidad del asiento: entre el borde del asiento y la parte trasera de la rodilla debe quedar un hueco de 2-4 dedos. Si el asiento es muy profundo y no se regula, la espalda no llega al respaldo.",
          "Reposabrazos en altura y, a ser posible, en anchura: los hombros deben quedar relajados, no encogidos ni caídos. Los reposabrazos fijos son el motivo más habitual de que una silla \"barata\" resulte incómoda para alguien de complexión distinta a la media.",
          "Inclinación del respaldo con bloqueo: poder reclinarse un poco y bloquear la posición ayuda en videollamadas largas; que solo se incline sin bloquear cansa más que no tener inclinación.",
        ],
      },
      {
        heading: "Apoyo lumbar: fijo, regulable o ninguno",
        body: [
          "El apoyo lumbar regulable en altura es el que mejor se adapta si varias personas van a usar la silla o si tu mesa cambia de altura (escritorio eléctrico). Un apoyo lumbar fijo bien colocado también funciona, pero solo si tu estatura encaja con dónde lo puso el fabricante.",
          "Desconfía de sillas que anuncian \"soporte lumbar\" sin ninguna pieza física diferenciada: a veces es solo una curva del tapizado, no un apoyo real.",
        ],
      },
      {
        heading: "Malla o tapizado",
        body: [
          "La malla (mesh) transpira mejor y suele envejecer mejor en climas cálidos, pero el tacto es más rígido. El tapizado acolchado es más cómodo al tacto y mejor para sesiones largas sentado quieto, pero acumula más calor.",
          "Si tu despacho no tiene aire acondicionado en verano, la malla se nota. Si trabajas muchas horas seguidas sin levantarte, el acolchado se agradece.",
        ],
      },
      {
        heading: "Cuándo compensa pagar más",
        body: [
          "El salto de calidad más grande está entre una silla sin ninguna regulación y una con las cuatro regulaciones básicas (altura, profundidad, reposabrazos, inclinación con bloqueo): eso ya soluciona la mayoría de problemas posturales.",
          "A partir de ahí, pagar más suele comprar mejores materiales (malla más duradera, mecanismos más suaves, garantías más largas), no funciones nuevas. Si vas a usar la silla más de 6 horas al día, la garantía y la disponibilidad de recambios (ruedas, gas) importan tanto como el primer precio.",
        ],
      },
    ],
    checklist: [
      "Altura del asiento regulable y compatible con tu mesa",
      "Profundidad del asiento regulable o adecuada a tu estatura",
      "Reposabrazos regulables en altura",
      "Respaldo con inclinación bloqueable",
      "Apoyo lumbar real (pieza física, no solo forma del tapizado)",
      "Garantía de 2 años o más si vas a usarla a diario",
    ],
    faq: [
      {
        q: "¿Necesito una silla \"gaming\" o una de oficina?",
        a: "Para trabajar delante de un ordenador, una silla de oficina bien regulada suele ser más cómoda: el respaldo alto y el acolchado extra de las sillas gaming están pensados para reclinarse, no para mantener una postura de escritura durante horas.",
      },
      {
        q: "¿La malla es siempre mejor que el tapizado?",
        a: "No, depende del clima de tu habitación y de cuánto tiempo pasas sentado sin moverte. Es mejor en ambientes cálidos y para sesiones activas; el tapizado gana en confort estático y en ambientes fríos.",
      },
    ],
    products: [
      {
        asin: "B0G6X6NP4X",
        title: "EveryKip Silla Escritorio Ergonómica Ajustable",
        note: "Entrada de gama: regulaciones básicas y reposacabezas, para quien empieza con presupuesto ajustado.",
        img: "https://m.media-amazon.com/images/I/71McE9pFyHL._AC_SF480,480_.jpg",
        price: "39",
        rating: "4,1★",
      },
      {
        asin: "B0F2TF6VV9",
        title: "naspaluro Silla Escritorio Ergonómica",
        note: "Buena valoración en su rango de precio, con soporte lumbar y ruedas suaves.",
        img: "https://m.media-amazon.com/images/I/81VzuM4bcCL._AC_SF480,480_.jpg",
        price: "56",
        rating: "4,5★",
      },
      {
        asin: "B0DZF9B1C3",
        title: "SONGMICS Silla de Oficina, malla de doble capa",
        note: "Malla transpirable, marca consolidada en mobiliario de oficina.",
        img: "https://m.media-amazon.com/images/I/71IGruWmItL._AC_SF480,480_.jpg",
        price: "67",
        rating: "4,0★",
      },
      {
        asin: "B0H3Q1Z43X",
        title: "Marsail Silla Oficina Ergonómica con reposacabezas 2D",
        note: "Reposabrazos plegables 3D y soporte lumbar 2D: cubre las cuatro regulaciones básicas.",
        img: "https://m.media-amazon.com/images/I/61kAuTzIbUL._AC_SF480,480_.jpg",
        price: "93",
        rating: "4,6★",
      },
      {
        asin: "B09B83Y8S1",
        title: "Amazon Basics Silla ejecutiva ergonómica",
        note: "Respaldo alto, reposacabezas y reposabrazos ajustables; garantía Amazon.",
        img: "https://m.media-amazon.com/images/I/61CwRpQn9DL._AC_SF480,480_.jpg",
        price: "134",
        rating: "4,0★",
      },
      {
        asin: "B0GWRDPZZF",
        title: "Bravo Silla Escritorio Silla Oficina Ergonomica",
        note: "Valoración muy alta; gama media con buenos materiales.",
        img: "https://m.media-amazon.com/images/I/71OYinawT9L._AC_SF480,480_.jpg",
        price: "169",
        rating: "4,8★",
      },
      {
        asin: "B0H3ZVDKYV",
        title: "FLEXISPOT ErgoX Lite Silla de Oficina Ergonómica",
        note: "Gama alta: el salto de materiales y durabilidad del que habla esta guía.",
        img: "https://m.media-amazon.com/images/I/61acaeEmewL._AC_SF480,480_.jpg",
        price: "299",
        rating: "4,2★",
      },
      {
        asin: "B0D6W5QB3F",
        title: "Silla de Oficina Ergonómica con Ruedas, Reposacabezas y Reposabrazos Ajustables",
        note: "La más económica de la selección con reposacabezas y reposabrazos ajustables de serie.",
        img: "https://m.media-amazon.com/images/I/61wmW0wAuPL._AC_SF480,480_.jpg",
        price: "57",
        rating: "4,3★",
      },
      {
        asin: "B07ZCM9YH1",
        title: "SONGMICS Silla de Oficina, de Malla, Ergonómica, Soporte Lumbar, Sin Reposacabezas",
        note: "Malla ligera sin reposacabezas: para quien no lo necesita y prioriza precio y transpirabilidad.",
        img: "https://m.media-amazon.com/images/I/81pA0ACpAPL._AC_SF480,480_.jpg",
        price: "65",
        rating: "4,4★",
      },
      {
        asin: "B0F9LJ2BNX",
        title: "JUPPLIES Silla Escritorio Ergonómica con Soporte Lumbar y Reposabrazos Plegables",
        note: "Reclinable con soporte lumbar y reposabrazos plegables; buena relación calidad-precio en gama baja-media.",
        img: "https://m.media-amazon.com/images/I/81dgP73ZcDL._AC_SF480,480_.jpg",
        price: "75",
        rating: "4,3★",
      },
      {
        asin: "B07TDPZM2K",
        title: "Yaheetech Silla de Oficina Ergonómica con Soporte Lumbar",
        note: "Soporte lumbar dedicado y marca con buen recorrido en sillas de oficina de gama media.",
        img: "https://m.media-amazon.com/images/I/71+oORv6v8L._AC_SF480,480_.jpg",
        price: "90",
        rating: "4,2★",
      },
      {
        asin: "B08DR42HFV",
        title: "NOBLEWELL Silla de Oficina Ergonómica con Reposacabezas 2D",
        note: "Reposacabezas 2D e inclinación de 130°; gama media con acolchado más grueso.",
        img: "https://m.media-amazon.com/images/I/61HF22fzVrL._AC_SF480,480_.jpg",
        price: "105",
        rating: "4,2★",
      },
      {
        asin: "B09GNPLXMZ",
        title: "Ticova Silla de Oficina Ergonómica con Función Mecedora",
        note: "Respaldo alto con función mecedora y reposabrazos 3D, valorada para sesiones largas.",
        img: "https://m.media-amazon.com/images/I/61tCKoGwAUL._AC_SF480,480_.jpg",
        price: "150",
        rating: "4,5★",
      },
      {
        asin: "B07GNDDNMW",
        title: "SIHOO M18 Silla Oficina Ergonómica, Soporte Lumbar Ajustable",
        note: "Soporte lumbar ajustable y hasta 150 kg de carga; marca especializada en ergonomía de oficina.",
        img: "https://m.media-amazon.com/images/I/61nb9ErcVpL._AC_SF480,480_.jpg",
        price: "200",
        rating: "4,4★",
      },
      {
        asin: "B0H82GP8LL",
        title: "SIHOO B300 Pro Silla Ergonómica Oficina, Soporte Lumbar Adaptativo",
        note: "Gama alta de SIHOO con soporte lumbar adaptativo: el salto de materiales más caro de la selección.",
        img: "https://m.media-amazon.com/images/I/61eJS0tejUL._AC_SF480,480_.jpg",
        price: "247",
        rating: "4,5★",
      },
    ],
  },
  {
    slug: "monitores",
    title: "Cómo elegir un monitor para trabajar (sin gastar de más)",
    dek: "Tamaño, resolución, distancia de trabajo y cuándo un segundo monitor rinde más que uno grande.",
    updated: "2026-09-14",
    img: "/assets/img/guias/monitores.jpg",
    intro: [
      "El error más habitual al elegir monitor para trabajar es fijarse solo en el tamaño en pulgadas y olvidar la resolución y la distancia a la que vas a sentarte. Un monitor grande con poca resolución se ve borroso de cerca; uno pequeño con mucha resolución obliga a poner el texto enorme para leerlo.",
    ],
    sections: [
      {
        heading: "Tamaño y resolución van juntos",
        body: [
          "Para trabajar con texto y hojas de cálculo a una distancia de escritorio normal (50-70 cm), la combinación que mejor funciona es 24-27 pulgadas con resolución 1440p (QHD). Con 1080p en 27 pulgadas o más, el texto se ve con menos definición porque los píxeles se estiran.",
          "Si vas a hacer edición de foto o vídeo, 4K en 27-32 pulgadas da mucho más espacio útil, pero exige una tarjeta gráfica capaz de moverlo con soltura y, a veces, escalado en el sistema operativo para que el texto no salga diminuto.",
        ],
      },
      {
        heading: "Panel: IPS, VA o TN",
        body: [
          "IPS es el estándar razonable para trabajo de oficina y diseño: buenos ángulos de visión y color fiel. VA da más contraste (negros más profundos) pero peor respuesta en movimiento. TN es el más barato y el que peor se ve desde el lateral: solo tiene sentido si el presupuesto manda por encima de todo.",
        ],
      },
      {
        heading: "Un monitor grande vs. dos monitores",
        body: [
          "Un monitor ultrawide (34\" o más) sustituye bien a dos monitores si tu trabajo es sobre todo lectura y escritura continua, porque no tienes el marco partiendo la vista. Dos monitores separados son mejores si necesitas mover ventanas completas de un lado a otro (por ejemplo, videollamada en uno y documento en otro) o si tu mesa no tiene espacio para curvar la vista hacia un panel muy ancho.",
          "El soporte importa tanto como el panel: un brazo articulado con ajuste de altura evita tener que elevar el monitor con libros y libera espacio de mesa. Si el monitor solo trae una peana fija baja, casi siempre conviene sumarle un soporte VESA aparte.",
        ],
      },
    ],
    checklist: [
      "Resolución acorde al tamaño (mínimo 1440p a partir de 27\")",
      "Panel IPS si vas a mirarlo desde ángulos o haces trabajo de color",
      "Altura regulable, con brazo VESA si la peana no ajusta bien",
      "Filtro de luz azul / modo lectura para sesiones largas",
      "Al menos una entrada USB-C si tu portátil la tiene (carga + vídeo por un solo cable)",
    ],
    faq: [
      {
        q: "¿Merece la pena un monitor curvo para trabajar?",
        a: "Solo se nota realmente a partir de tamaños ultrawide grandes (34\" o más), donde la curva compensa la distancia extra a los bordes. En tamaños estándar de 24-27\" la curvatura aporta poco para trabajo de oficina.",
      },
      {
        q: "¿Necesito 144Hz para trabajar?",
        a: "No: la frecuencia de refresco alta se nota en juegos y en el movimiento del cursor, pero para texto, hojas de cálculo o navegación 60Hz es suficiente. Es una prioridad de presupuesto solo si también vas a jugar en ese monitor.",
      },
    ],
    products: [
      {
        asin: "B0GHVY7F4M",
        title: "Gawfolk 27\" IPS 2K QHD con altavoces",
        note: "Entrada a QHD real (no 1080p estirado) al precio más ajustado de la selección.",
        img: "https://m.media-amazon.com/images/I/71ojDLuE+bL._AC_SF480,480_.jpg",
        price: "108",
        rating: "4,5★",
      },
      {
        asin: "B0F9YSJJG2",
        title: "PHILIPS 27E2N1500L QHD IPS 75Hz",
        note: "Marca consolidada, panel IPS QHD para ofimática sin sobrepagar por Hz que no vas a usar.",
        img: "https://m.media-amazon.com/images/I/71LEo2ShJvL._AC_SF480,480_.jpg",
        price: "107",
        rating: "4,4★",
      },
      {
        asin: "B0DCZF5X4P",
        title: "Lenovo L27qe QHD IPS 100Hz",
        note: "Buen equilibrio precio/panel para trabajo diario con texto y hojas de cálculo.",
        img: "https://m.media-amazon.com/images/I/713eHE7tsTL._AC_SF480,480_.jpg",
        price: "119",
        rating: "4,4★",
      },
      {
        asin: "B096Y7MK8W",
        title: "MSI Pro MP273QW WQHD IPS 144Hz",
        note: "USB-C y ajuste de inclinación; punto medio de la gama para quien quiere margen de Hz.",
        img: "https://m.media-amazon.com/images/I/71RI4c3RFJL._AC_SF480,480_.jpg",
        price: "139",
        rating: "4,6★",
      },
      {
        asin: "B0GW8PLMZM",
        title: "DELL SE2726D QHD IPS 144Hz",
        note: "Marca con buen soporte y garantía; recomendable si valoras la posventa.",
        img: "https://m.media-amazon.com/images/I/71b7gL6FOPL._AC_SF480,480_.jpg",
        price: "152",
        rating: "4,6★",
      },
      {
        asin: "B0FWCJYML5",
        title: "LG Ultragear 27G610A-B IPS",
        note: "Gama alta de LG con buen soporte físico regulable en altura.",
        img: "https://m.media-amazon.com/images/I/71bwuRTTK8L._AC_SF480,480_.jpg",
        price: "159",
        rating: "4,6★",
      },
      {
        asin: "B0DH51BPZD",
        title: "LG Ultrafine 27US500-W 4K IPS HDR10",
        note: "Para edición de foto/vídeo: 4K real en 27\", el salto de resolución del que habla esta guía.",
        img: "https://m.media-amazon.com/images/I/718FZ6mbwjL._AC_SF480,480_.jpg",
        price: "164",
        rating: "4,6★",
      },
      {
        asin: "B0CX9CVS9Q",
        title: "PHILIPS 27E1N1100A Monitor 27\" FHD 120Hz IPS con Altavoces",
        note: "Entrada de gama a 27\": FHD con 120Hz, más fluido que un panel estándar de 60Hz al mismo precio.",
        img: "https://m.media-amazon.com/images/I/71+5xZyoyFL._AC_SF480,480_.jpg",
        price: "89",
        rating: "4,5★",
      },
      {
        asin: "B0FL366VPN",
        title: "LG Monitor Ultragear 27G411A-B 27\" IPS",
        note: "IPS de 27\" con buena valoración de marca a precio ajustado.",
        img: "https://m.media-amazon.com/images/I/716H-E70hvL._AC_SF480,480_.jpg",
        price: "95",
        rating: "4,4★",
      },
      {
        asin: "B0DJTDVCVT",
        title: "ASUS VY279HGR Monitor Eye Care Gaming IPS FHD 120Hz",
        note: "Filtro de luz azul y sin parpadeo (\"Eye Care\"): pensado para sesiones largas de pantalla.",
        img: "https://m.media-amazon.com/images/I/81Q+eTtM-CL._AC_SF480,480_.jpg",
        price: "101",
        rating: "4,6★",
      },
      {
        asin: "B0DSG3H6Y1",
        title: "Samsung Monitor Essential S3 S30DG FHD 27\" 100Hz",
        note: "Marca Samsung con modo Eye Saver; buena opción de gama media para ofimática.",
        img: "https://m.media-amazon.com/images/I/61U4zUws9BL._AC_SF480,480_.jpg",
        price: "105",
        rating: "4,6★",
      },
      {
        asin: "B0FWCLJ51V",
        title: "MSI Pro MP275QA 27\" WQHD IPS 144Hz",
        note: "QHD a 144Hz con la valoración más alta de la selección de monitores.",
        img: "https://m.media-amazon.com/images/I/71ixHRkWm8L._AC_SF480,480_.jpg",
        price: "129",
        rating: "4,9★",
      },
      {
        asin: "B0F9YXHXRH",
        title: "ASUS TUF Gaming VG27AQL5A Fast IPS QHD 210Hz",
        note: "QHD con 210Hz de refresco: gama alta si además usas el monitor para juego.",
        img: "https://m.media-amazon.com/images/I/713FGs0ALqL._AC_SF480,480_.jpg",
        price: "196",
        rating: "4,3★",
      },
      {
        asin: "B0GT69SMGQ",
        title: "XIAOMI Monitor Gaming Mini-LED 2K 27\" 180Hz HDR1000",
        note: "Panel Mini-LED con HDR1000: el salto de contraste más caro de la selección.",
        img: "https://m.media-amazon.com/images/I/71uXAVuME5L._AC_SF480,480_.jpg",
        price: "349",
        rating: "4,5★",
      },
      {
        asin: "B0F1DMQHP3",
        title: "MSI MAG 272URDF 27\" 4K UHD Rapid IPS",
        note: "4K UHD en 27\" con altura e inclinación ajustables; para quien necesita máxima resolución.",
        img: "https://m.media-amazon.com/images/I/71Yt6bWSZtL._AC_SF480,480_.jpg",
        price: "289",
        rating: "4,3★",
      },
    ],
  },
  {
    slug: "teclados-y-raton",
    title: "Teclado y ratón: guía para elegir sin dejarte el pulso en ello",
    dek: "Mecánico o de membrana, ergonómico o estándar, y cuándo cambiar de verdad mejora la muñeca.",
    updated: "2026-09-13",
    img: "/assets/img/guias/teclados-y-raton.jpg",
    intro: [
      "El teclado y el ratón son los periféricos que más tocas y los que menos tiempo se dedica a elegir bien. La diferencia entre un combo genérico y uno pensado para tu forma de trabajar se nota sobre todo en sesiones largas, no en los primeros cinco minutos probándolo en la tienda.",
    ],
    sections: [
      {
        heading: "Membrana o mecánico",
        body: [
          "Los teclados de membrana son más silenciosos y suelen bastar para escritura y ofimática normal. Los mecánicos dan una pulsación más consistente y son más duraderos a largo plazo, pero el ruido (sobre todo con switches clicky) puede ser un problema en oficina compartida o videollamadas: si es tu caso, busca switches \"silenciosos\" o \"lineales\", no \"clicky\".",
        ],
      },
      {
        heading: "Diseño ergonómico: cuándo tiene sentido",
        body: [
          "Un teclado dividido o con inclinación negativa (split o tenting) ayuda de verdad si ya notas molestia en la muñeca o el antebrazo al escribir mucho rato. Para quien no tiene molestias, el salto de un teclado estándar a uno ergonómico no es imprescindible, aunque tampoco hace daño.",
          "En ratones, la clave no es el tamaño sino el agarre: si usas agarre de palma (toda la mano apoyada), un ratón más grande y alto es más cómodo; si usas agarre de garra o de dedos, uno más bajo y compacto da más control.",
        ],
      },
      {
        heading: "Cable, Bluetooth o USB con receptor",
        body: [
          "Para trabajo diario en un único ordenador, el cable sigue siendo lo más fiable: cero pilas, cero latencia perceptible. Bluetooth gana si necesitas cambiar entre varios dispositivos (portátil y tablet, por ejemplo). Un receptor USB dedicado (no Bluetooth genérico) suele dar la mejor mezcla de comodidad y estabilidad de conexión.",
        ],
      },
    ],
    checklist: [
      "Switches silenciosos o lineales si trabajas en oficina compartida",
      "Reposamuñecas o inclinación negativa si ya notas molestias",
      "Tamaño de ratón acorde a tu tipo de agarre (palma, garra o dedos)",
      "Conexión con cable si la fiabilidad manda; Bluetooth si necesitas multidispositivo",
    ],
    faq: [
      {
        q: "¿Un teclado mecánico dura más que uno de membrana?",
        a: "Por lo general sí: los switches mecánicos suelen estar valorados para decenas de millones de pulsaciones, frente a los millones que aguanta una membrana antes de perder tacto. La diferencia se nota sobre todo después de varios años de uso intensivo.",
      },
    ],
    products: [
      {
        asin: "B00564NI9U",
        title: "Logitech K120, teclado con cable",
        note: "Membrana estándar con cable: la opción más fiable y barata para uso diario en un único equipo.",
        img: "https://m.media-amazon.com/images/I/61U-L2mrlRL._AC_SF480,480_.jpg",
        price: "12",
        rating: "4,6★",
      },
      {
        asin: "B0CPM5PGWM",
        title: "Trust ODY II, teclado inalámbrico silencioso",
        note: "Pulsación silenciosa, buena opción para oficina compartida o videollamadas.",
        img: "https://m.media-amazon.com/images/I/71sn+vXNv9L._AC_SF480,480_.jpg",
        price: "18",
        rating: "4,3★",
      },
      {
        asin: "B07W6J71BL",
        title: "Logitech Wave Keys, teclado ergonómico inalámbrico",
        note: "Curvatura e inclinación negativa: para quien ya nota molestia en la muñeca al escribir mucho.",
        img: "https://m.media-amazon.com/images/I/71s7K0xjGRL._AC_SF480,480_.jpg",
        price: "60",
        rating: "4,7★",
      },
      {
        asin: "B07W5JKPK4",
        title: "Logitech G G413 SE, teclado mecánico",
        note: "Switches mecánicos para quien prioriza pulsación consistente y durabilidad a largo plazo.",
        img: "https://m.media-amazon.com/images/I/619re9p8nlL._AC_SF480,480_.jpg",
        price: "61",
        rating: "4,5★",
      },
      {
        asin: "B07FLZ3XSK",
        title: "Trust Verto, ratón vertical con cable",
        note: "Entrada al agarre vertical: reduce la torsión de muñeca sin gastar apenas nada.",
        img: "https://m.media-amazon.com/images/I/61zdXL7k6eL._AC_SF480,480_.jpg",
        price: "11",
        rating: "4,4★",
      },
      {
        asin: "B010R7IX5E",
        title: "TECKNET ratón inalámbrico estándar",
        note: "Para agarre de palma: tamaño estándar, pila de hasta 24 meses.",
        img: "https://m.media-amazon.com/images/I/61ARJDf28dL._AC_SF480,480_.jpg",
        price: "11",
        rating: "4,5★",
      },
      {
        asin: "B0CZ939BSB",
        title: "TECKNET ratón ergonómico vertical recargable",
        note: "6 botones y varios niveles de DPI; buen punto medio de precio y prestaciones.",
        img: "https://m.media-amazon.com/images/I/61O-PIjLwgL._AC_SF480,480_.jpg",
        price: "21",
        rating: "4,5★",
      },
      {
        asin: "B0D12PGGKK",
        title: "ProtoArc EM11 NL, ratón vertical inalámbrico",
        note: "La opción mejor valorada de la categoría vertical en esta selección.",
        img: "https://m.media-amazon.com/images/I/511qcVCPKbL._AC_SF480,480_.jpg",
        price: "27",
        rating: "4,6★",
      },
      {
        asin: "B09ZDZX8T2",
        title: "Cherry KC 4500 Ergo, teclado ergonómico curvo con cable",
        note: "Teclado curvo con cable y reposamuñecas de espuma de memoria: ergonomía clásica sin depender de pilas.",
        img: "https://m.media-amazon.com/images/I/61cPP5iAqJL._AC_SF480,480_.jpg",
        price: "40",
        rating: "3,7★",
      },
      {
        asin: "B07FQNBZ3R",
        title: "Perixx PERIBOARD-512 teclado ergonómico dividido con cable",
        note: "Diseño dividido con cable a precio contenido, para quien quiere separar las manos sin ir a inalámbrico.",
        img: "https://m.media-amazon.com/images/I/61qFKjcLloL._AC_SF480,480_.jpg",
        price: "50",
        rating: "4,2★",
      },
      {
        asin: "B07W4DHXFT",
        title: "Logitech Signature K650 teclado inalámbrico con reposamanos",
        note: "Reposamanos integrado de serie; gama media para quien no quiere comprarlo aparte.",
        img: "https://m.media-amazon.com/images/I/619Pp3PzRlL._AC_SF480,480_.jpg",
        price: "49",
        rating: "4,3★",
      },
      {
        asin: "B07W7L66L8",
        title: "Logitech Ergo K860 teclado partido inalámbrico",
        note: "Gama alta: teclado completamente partido con inclinación negativa, la opción más ergonómica de la selección.",
        img: "https://m.media-amazon.com/images/I/81X3LIHz6+L._AC_SF480,480_.jpg",
        price: "96",
        rating: "4,5★",
      },
      {
        asin: "B0DFBV17B1",
        title: "TECKNET Ratón Bluetooth Ergonómico Vertical, hasta 4800 dpi",
        note: "Conexión dual Bluetooth y USB, con varios niveles de dpi ajustables a buen precio.",
        img: "https://m.media-amazon.com/images/I/618-YKhXsgL._AC_SF480,480_.jpg",
        price: "25",
        rating: "4,5★",
      },
      {
        asin: "B0DR1K3DM1",
        title: "UGREEN Ratón Ergonómico Inalámbrico Vertical 4000 dpi",
        note: "La opción vertical más económica de la selección, con seis botones y agarre cómodo.",
        img: "https://m.media-amazon.com/images/I/61gGSD7pivL._AC_SF480,480_.jpg",
        price: "18",
        rating: "4,4★",
      },
      {
        asin: "B07W4DGC27",
        title: "Logitech Lift, ratón ergonómico vertical",
        note: "Gama alta de ratón vertical: mejor acabado y precisión que las opciones de entrada.",
        img: "https://m.media-amazon.com/images/I/61IuKPhnVJL._AC_SF480,480_.jpg",
        price: "50",
        rating: "4,5★",
      },
    ],
  },
  {
    slug: "iluminacion-escritorio",
    title: "Iluminación de escritorio: cómo evitar el cansancio de vista",
    dek: "Temperatura de color, posición del flexo y por qué la luz del monitor no basta.",
    updated: "2026-09-12",
    img: "/assets/img/guias/iluminacion-escritorio.jpg",
    intro: [
      "Trabajar solo con la luz del monitor encendido en una habitación oscura es una de las causas más comunes de fatiga visual, aunque casi nadie lo relaciona con eso: el contraste tan fuerte entre la pantalla brillante y el resto a oscuras obliga al ojo a reajustarse constantemente.",
    ],
    sections: [
      {
        heading: "Luz ambiental antes que luz de tarea",
        body: [
          "Lo primero es tener una luz general en la habitación, aunque sea suave, para que el contraste con la pantalla no sea tan brusco. La luz de flexo o de barra sobre el monitor es un complemento para el papel y el teclado, no un sustituto de la luz ambiental.",
        ],
      },
      {
        heading: "Temperatura de color",
        body: [
          "Para trabajo de día, una luz blanca neutra (4000-5000K) mantiene el estado de alerta sin resultar tan fría como la luz de oficina clásica. Por la tarde-noche, bajar a tonos más cálidos (2700-3500K) ayuda a no interferir tanto con el sueño si trabajas hasta tarde.",
          "Las lámparas con temperatura regulable (no solo intensidad) son las que mejor se adaptan a lo largo del día; muchas barras de luz para monitor ya lo incorporan.",
        ],
      },
      {
        heading: "Posición: evitar reflejos, no solo iluminar",
        body: [
          "Un flexo colocado justo delante del monitor genera reflejo en la pantalla. Lo habitual es colocarlo lateral, ligeramente por delante del monitor, o usar una barra de luz que se engancha sobre el propio monitor y apunta hacia el escritorio, no hacia la pantalla.",
        ],
      },
    ],
    checklist: [
      "Luz ambiental en la habitación, no solo la del monitor",
      "Temperatura de color regulable (neutra de día, cálida de noche)",
      "Flexo o barra de luz colocados sin generar reflejo en la pantalla",
      "Intensidad regulable para no deslumbrar en videollamadas",
    ],
    faq: [
      {
        q: "¿Las barras de luz para monitor son mejores que un flexo normal?",
        a: "No son \"mejores\" en general, pero resuelven bien un problema concreto: iluminan el escritorio sin ocupar espacio de mesa ni generar reflejo en la pantalla, porque se enganchan sobre el borde superior del monitor y apuntan hacia abajo.",
      },
    ],
    products: [
      {
        asin: "B08MJJN9YF",
        title: "Lepro Lámpara Escritorio LED 800LM regulable",
        note: "Flexo básico con intensidad regulable; opción más barata para tener ya luz de tarea.",
        img: "https://m.media-amazon.com/images/I/41YheQguQTL._AC_SF480,480_.jpg",
        price: "20",
        rating: "4,7★",
      },
      {
        asin: "B0FCS4D8P1",
        title: "Flexo LED 15W con USB-C, 3 temperaturas de color",
        note: "Temperatura regulable (neutra de día, cálida de noche), el criterio clave de esta guía.",
        img: "https://m.media-amazon.com/images/I/71iWf8QCMrL._AC_SF480,480_.jpg",
        price: "19",
        rating: "4,4★",
      },
      {
        asin: "B0FJ8PM4CK",
        title: "Caldarax Flexo LED con temporizador",
        note: "10 niveles de brillo y control táctil; buen punto medio de prestaciones.",
        img: "https://m.media-amazon.com/images/I/712OANxQ37L._AC_SF480,480_.jpg",
        price: "22",
        rating: "4,5★",
      },
      {
        asin: "B0FB99V6G5",
        title: "Flexo LED 24W con mando a distancia y pinza",
        note: "Gama alta de flexo: más potencia e instalación con pinza en vez de peana.",
        img: "https://m.media-amazon.com/images/I/71JtN-jHlcL._AC_SF480,480_.jpg",
        price: "45",
        rating: "4,3★",
      },
      {
        asin: "B0GGXPFW9X",
        title: "Yeelight Screenbar, barra de luz para monitor",
        note: "Se engancha sobre el monitor y apunta al escritorio: cero reflejo en pantalla, cero espacio de mesa.",
        img: "https://m.media-amazon.com/images/I/617eohKDxLL._AC_SF480,480_.jpg",
        price: "39",
        rating: "4,6★",
      },
      {
        asin: "B08DKQ3JG1",
        title: "Quntis Lámpara Monitor con control táctil",
        note: "Control táctil y mando a distancia; buena opción de gama media en barra de luz.",
        img: "https://m.media-amazon.com/images/I/51p1Ui5sa7L._AC_SF480,480_.jpg",
        price: "49",
        rating: "4,6★",
      },
      {
        asin: "B0CR1H394H",
        title: "Quntis 51cm con retroiluminación y control inalámbrico",
        note: "Gama alta: cubre pantallas más anchas y añade retroiluminación ambiental.",
        img: "https://m.media-amazon.com/images/I/61cbO+mNV6L._AC_SF480,480_.jpg",
        price: "61",
        rating: "4,6★",
      },
      {
        asin: "B0G3QKW8QM",
        title: "Flexo de escritorio con luz nocturna, control táctil y puerto USB",
        note: "El más barato de la selección: 5 modos y 10 niveles de brillo por menos de 12€.",
        img: "https://m.media-amazon.com/images/I/410r9AqEQLL._AC_SF480,480_.jpg",
        price: "12",
        rating: "4,4★",
      },
      {
        asin: "B0C4GDGR63",
        title: "iFalarila Lámpara de escritorio regulable con 160 LED y cuello de cisne",
        note: "Cuello de cisne flexible con abrazadera en C o clip: se fija a la mesa sin peana.",
        img: "https://m.media-amazon.com/images/I/71uxR31Qn0L._AC_SF480,480_.jpg",
        price: "24",
        rating: "4,6★",
      },
      {
        asin: "B0CTZXNX3D",
        title: "Aigostar Flexo LED Escritorio táctil, cuello flexible 360°",
        note: "Marca consolidada con memoria de última posición de brillo y color.",
        img: "https://m.media-amazon.com/images/I/51BkjFG68SL._AC_SF480,480_.jpg",
        price: "37",
        rating: "4,7★",
      },
      {
        asin: "B074JF5LWN",
        title: "B.K.Licht Lámpara de escritorio tipo arquitecto, brazo articulado vintage",
        note: "Diseño distinto a los flexos LED modernos: brazo articulado clásico de estilo retro.",
        img: "https://m.media-amazon.com/images/I/6110IlZNAoL._AC_SF480,480_.jpg",
        price: "25",
        rating: "4,4★",
      },
      {
        asin: "B0D1KB3VPD",
        title: "KableRika Lámpara de escritorio LED de doble cabezal con base metálica",
        note: "Doble cabezal orientable de forma independiente; gama alta de flexo con base metálica sólida.",
        img: "https://m.media-amazon.com/images/I/71p4sheXbiL._AC_SF480,480_.jpg",
        price: "63",
        rating: "4,6★",
      },
      {
        asin: "B0G2RH6K2D",
        title: "KableRika Barra de luz con 3 paneles y base, para escritorio",
        note: "Alternativa de gama alta a la barra sobre monitor: ilumina el escritorio entero con temporizador.",
        img: "https://m.media-amazon.com/images/I/719Fy7YbbUL._AC_SF480,480_.jpg",
        price: "70",
        rating: "5,0★",
      },
      {
        asin: "B0GYC3CY5B",
        title: "Comely Lámpara de escritorio 24W, 120cm, 5 temperaturas de color",
        note: "La más potente en lúmenes de la selección (2750LM), con pinza y 10 niveles de brillo.",
        img: "https://m.media-amazon.com/images/I/71PcpyIQHEL._AC_SF480,480_.jpg",
        price: "59",
        rating: "5,0★",
      },
    ],
  },
  {
    slug: "organizacion-cables-y-espacio",
    title: "Organización del escritorio: cables, espacio y accesorios que sí sirven",
    dek: "Qué accesorios de orden marcan una diferencia real y cuáles son solo estética.",
    updated: "2026-09-10",
    img: "/assets/img/guias/organizacion-cables-y-espacio.jpg",
    intro: [
      "Un escritorio despejado no es solo estética: menos cables sueltos significa menos enganchones, menos polvo acumulado y más espacio real para trabajar. Pero no todos los accesorios de \"organización\" que se venden aportan lo mismo.",
    ],
    sections: [
      {
        heading: "Lo que de verdad cambia el día a día",
        body: [
          "Una bandeja pasacables bajo la mesa saca de la vista el nudo de cargadores y regletas, que es normalmente el mayor foco de desorden visual. Un organizador vertical de documentos libera superficie horizontal, que suele ser el recurso más escaso en escritorios pequeños.",
          "Una regleta con USB integrado reduce el número de cargadores independientes sobre la mesa, que es otra fuente habitual de cables cruzados.",
        ],
      },
      {
        heading: "Lo que suele ser más estética que función",
        body: [
          "Los organizadores decorativos de escritorio (portalápices, bandejitas) ayudan poco si el problema real son los cables; conviene resolver primero el cableado y después pensar en estética.",
          "Las alfombrillas XL son cómodas pero no \"organizan\" nada por sí solas: son una mejora de confort, no de orden.",
        ],
      },
    ],
    checklist: [
      "Bandeja pasacables o canaleta bajo la mesa",
      "Regleta con USB para reducir cargadores sueltos",
      "Organizador vertical de documentos si el espacio horizontal escasea",
      "Brazo de monitor si la peana ocupa demasiada mesa",
    ],
    faq: [
      {
        q: "¿Por dónde empiezo si tengo el escritorio muy desordenado?",
        a: "Por los cables: suelen ser la causa visual del desorden aunque no lo parezca. Agrupar y recoger cables con una bandeja o canaleta suele dar más sensación de orden que cualquier accesorio decorativo.",
      },
    ],
    products: [
      {
        asin: "B0F61ZJ37M",
        title: "Bandeja pasacables bajo mesa, sin taladro",
        note: "El accesorio que más cambia el desorden visual, según esta guía: esconde el nudo de cargadores.",
        img: "https://m.media-amazon.com/images/I/81iE+cj0ZQL._AC_SF480,480_.jpg",
        price: "16",
        rating: "4,7★",
      },
      {
        asin: "B0BFWGLVLX",
        title: "Amazon Basics, caja organizadora de cables",
        note: "Alternativa cerrada tipo caja en vez de bandeja abierta; oculta regletas enteras.",
        img: "https://m.media-amazon.com/images/I/51B-Ca4dcoL._AC_SF480,480_.jpg",
        price: "18",
        rating: "4,6★",
      },
      {
        asin: "B0GT8V2JVZ",
        title: "Regleta de 5 enchufes con USB",
        note: "Reduce cargadores independientes sobre la mesa, otra fuente habitual de cables cruzados.",
        img: "https://m.media-amazon.com/images/I/61yjbMen6GL._AC_SF480,480_.jpg",
        price: "30",
        rating: "4,8★",
      },
      {
        asin: "B0DM9J2NK7",
        title: "Toma de mesa con USB y sujeción a la mesa",
        note: "Se fija al borde del escritorio: enchufes y USB a mano sin cable colgando.",
        img: "https://m.media-amazon.com/images/I/61ZKUNfetaL._AC_SF480,480_.jpg",
        price: "31",
        rating: "4,7★",
      },
      {
        asin: "B07VQJ33FS",
        title: "D.RECT Organizador metálico de 3 bandejas A4",
        note: "Libera superficie horizontal apilando documentos en vertical, el recurso más escaso en mesas pequeñas.",
        img: "https://m.media-amazon.com/images/I/81I6g0PbrJL._AC_SF480,480_.jpg",
        price: "16",
        rating: "4,4★",
      },
      {
        asin: "B0FR1YWMS3",
        title: "Organizador de escritorio metal, 4 compartimentos",
        note: "Más capacidad vertical si manejas varias carpetas o revistas a la vez.",
        img: "https://m.media-amazon.com/images/I/8106zbAB2YL._AC_SF480,480_.jpg",
        price: "20",
        rating: "4,6★",
      },
      {
        asin: "B0CGX7BY2T",
        title: "Suptek Brazo de monitor regulable, VESA 75/100",
        note: "Si la peana del monitor ocupa demasiada mesa: libera espacio horizontal y ajusta la altura.",
        img: "https://m.media-amazon.com/images/I/61v-jjGCyuL._AC_SF480,480_.jpg",
        price: "21",
        rating: "4,6★",
      },
      {
        asin: "B0BM68LZW4",
        title: "Organizador de cables de malla flexible bajo mesa, hasta 10 kg",
        note: "Alternativa de malla a la bandeja rígida: se adapta a cualquier ancho de mesa.",
        img: "https://m.media-amazon.com/images/I/712gQXzzjAL._AC_SF480,480_.jpg",
        price: "25",
        rating: "4,6★",
      },
      {
        asin: "B0HG21H1SM",
        title: "edihome Caja organizadora de cables para escritorio y TV, con ventilación",
        note: "Oculta regletas y router enteros en una caja ventilada, en vez de dejarlos a la vista.",
        img: "https://m.media-amazon.com/images/I/61wPPDAULtL._AC_SF480,480_.jpg",
        price: "13",
        rating: "4,7★",
      },
      {
        asin: "B0DXDVLV4W",
        title: "UGREEN 6 piezas clip de cable de resorte con rotación de 91°",
        note: "Fijación puntual muy barata para ordenar tramos cortos de cable sin comprar una bandeja entera.",
        img: "https://m.media-amazon.com/images/I/61UGOC37W7L._AC_SF480,480_.jpg",
        price: "8",
        rating: "4,7★",
      },
      {
        asin: "B08N1HX647",
        title: "PAMO Canaleta para cables de escritorio, 2 unidades",
        note: "Canaleta rígida en vez de bandeja: esconde el cableado que corre pegado a la pared o la mesa.",
        img: "https://m.media-amazon.com/images/I/71UAtzA1IzL._AC_SF480,480_.jpg",
        price: "35",
        rating: "4,7★",
      },
      {
        asin: "B0928VJDZ3",
        title: "SOULWIT Kit de organización de cables de 200 piezas",
        note: "Kit completo con fundas, clips y bridas para quien prefiere resolver todo el cableado de una vez.",
        img: "https://m.media-amazon.com/images/I/71QZyAbn2ML._AC_SF480,480_.jpg",
        price: "20",
        rating: "4,7★",
      },
      {
        asin: "B0G1C95LXP",
        title: "Organizador de cables para escritorio ajustable 64-98 cm, sin taladro",
        note: "Se adapta a distintos anchos de mesa sin necesidad de taladrar ni fijar con cinta.",
        img: "https://m.media-amazon.com/images/I/71wSXXS81sL._AC_SF480,480_.jpg",
        price: "28",
        rating: "4,5★",
      },
      {
        asin: "B0F8BV9GTR",
        title: "Set de 3 cajas organizadoras de cables con tapa de bambú",
        note: "La opción con más estética de la selección, aunque conviene resolver primero el cableado en sí.",
        img: "https://m.media-amazon.com/images/I/61RaGxlo22L._AC_SF480,480_.jpg",
        price: "24",
        rating: "4,2★",
      },
    ],
  },
  {
    slug: "mesas-elevables",
    title: "Mesas elevables: cuándo compensa pasar a un escritorio de pie",
    dek: "Motor único o doble, tamaño de tablero y qué mirar antes de comprar un escritorio regulable en altura.",
    updated: "2026-09-17",
    img: "/assets/img/guias/mesas-elevables.jpg",
    intro: [
      "Una mesa elevable no sustituye a moverse durante el día, pero facilita muchísimo alternar entre sentado y de pie sin tener que levantarte de la silla para ajustar nada: basta con pulsar un botón o recuperar una posición guardada.",
      "El salto de precio entre modelos es grande, y no siempre corresponde a lo que de verdad se nota en el uso diario. Esta guía explica qué diferencias importan y cuáles son solo marketing.",
    ],
    sections: [
      {
        heading: "Motor único o doble motor",
        body: [
          "Las mesas con motor único (uno de los dos pies no tiene motor, solo se desliza) son más baratas y bastan para tableros pequeños o medianos. Las de doble motor suben más rápido, de forma más uniforme y soportan más peso sin perder estabilidad: se nota sobre todo con tableros grandes (160 cm o más) o con mucho peso encima (monitores, brazo de monitor, torre de PC).",
          "Si tu tablero mide más de 140 cm de ancho o vas a cargarlo con varios monitores, el doble motor deja de ser un lujo y pasa a ser lo que evita que la mesa vibre o se desnivele al subir.",
        ],
      },
      {
        heading: "Funciones de memoria y anticolisión",
        body: [
          "Guardar 2-4 alturas de memoria (una para sentado, otra para de pie) es lo que hace que realmente uses la función de elevar la mesa: sin memoria, hay que reajustar la altura a ojo cada vez, y eso desanima a usarla a diario.",
          "El sistema anticolisión detiene la mesa si detecta un obstáculo al subir o bajar (una silla, un cajón abierto). No es imprescindible, pero evita sustos si hay niños o mascotas cerca del escritorio.",
        ],
      },
      {
        heading: "Tamaño de tablero y qué va encima",
        body: [
          "Para un puesto con un monitor y poco más, 120x60 cm es suficiente. Si usas dos monitores, un portátil aparte o un brazo de monitor, conviene subir a 140-160 cm de ancho para no quedarte sin espacio al ajustar la altura.",
          "El rango de altura también importa: comprueba que la mesa baje lo suficiente para tu altura sentado (normalmente 70-72 cm) y suba lo suficiente para tu altura de pie con los codos a 90°.",
        ],
      },
    ],
    checklist: [
      "Doble motor si el tablero supera 140 cm o carga varios monitores",
      "Al menos 2 alturas de memoria guardadas",
      "Rango de altura que cubra tu postura sentado y de pie",
      "Sistema anticolisión si hay niños o mascotas cerca",
      "Capacidad de carga acorde a lo que va a llevar encima (monitores, brazo, torre)",
    ],
    faq: [
      {
        q: "¿Merece la pena una mesa elevable si ya tengo una silla ergonómica buena?",
        a: "Sí, son complementarias: la silla resuelve la postura sentado, pero solo la mesa elevable permite alternar a estar de pie sin cambiar de mueble. Alternar posturas a lo largo del día reduce más la fatiga que cualquier mejora de silla por sí sola.",
      },
      {
        q: "¿Es muy ruidoso subir y bajar la mesa?",
        a: "En los modelos de gama media y alta, el motor apenas se nota; los eléctricos actuales son mucho más silenciosos que los primeros modelos del mercado. Es un aspecto donde sí suele notarse la diferencia entre marcas económicas y especializadas.",
      },
    ],
    products: [
      {
        asin: "B0GQKLHPZZ",
        title: "WOLTU Escritorio Elevable Eléctrico 80x48 cm",
        note: "Entrada de gama: tamaño compacto para un puesto sencillo con un único monitor.",
        img: "https://m.media-amazon.com/images/I/61sQ4qq7-NL._AC_SF480,480_.jpg",
        price: "73",
        rating: "4,7★",
      },
      {
        asin: "B0FYYGGYPZ",
        title: "Escritorio Elevable Eléctrico 120x60 cm con tablero ensamblado",
        note: "Tamaño estándar a precio muy ajustado, motor único suficiente para uso doméstico.",
        img: "https://m.media-amazon.com/images/I/71YAQ41RRfL._AC_SF480,480_.jpg",
        price: "85",
        rating: "4,7★",
      },
      {
        asin: "B0F98GXZWG",
        title: "HUANUO Escritorio Eléctrico Regulable 80x48 cm, 4 memorias",
        note: "Tamaño compacto con 4 alturas memorizables, buen punto de entrada con función de memoria.",
        img: "https://m.media-amazon.com/images/I/61U0DUlJOuL._AC_SF480,480_.jpg",
        price: "85",
        rating: "4,6★",
      },
      {
        asin: "B0D9MGDDHD",
        title: "ErGear Escritorio Elevable Eléctrico 120x60 cm",
        note: "Tamaño estándar de marca especializada en mesas elevables, buena relación precio-tamaño.",
        img: "https://m.media-amazon.com/images/I/61lAmcbUAjL._AC_SF480,480_.jpg",
        price: "95",
        rating: "4,6★",
      },
      {
        asin: "B0FSQ8W2C1",
        title: "VASAGLE Escritorio Eléctrico Ajustable en Altura 100x60 cm",
        note: "Marca consolidada en mobiliario de oficina; tamaño algo más reducido a precio de entrada.",
        img: "https://m.media-amazon.com/images/I/71AyU88o8xL._AC_SF480,480_.jpg",
        price: "76",
        rating: "4,6★",
      },
      {
        asin: "B0CF2CB96N",
        title: "VASAGLE Escritorio Elevable Eléctrico con 4 Memorias y Ruedas",
        note: "Incorpora ruedas para poder moverla de sitio, algo poco habitual en esta categoría.",
        img: "https://m.media-amazon.com/images/I/715j8-bFkPL._AC_SF480,480_.jpg",
        price: "102",
        rating: "4,2★",
      },
      {
        asin: "B0GR99D6LM",
        title: "VASAGLE Escritorio Elevable Eléctrico con Motor Silencioso y USB-C",
        note: "Puerto USB-C integrado y motor especialmente silencioso; gama media con detalle moderno.",
        img: "https://m.media-amazon.com/images/I/71AsAJ7quoL._AC_SF480,480_.jpg",
        price: "106",
        rating: "4,2★",
      },
      {
        asin: "B0FQBQFZR5",
        title: "ErGear Escritorio Elevable Eléctrico 160x80 cm",
        note: "Tablero grande para dos monitores o brazo de monitor; sigue siendo motor único.",
        img: "https://m.media-amazon.com/images/I/71WHyC4Li6L._AC_SF480,480_.jpg",
        price: "136",
        rating: "4,6★",
      },
      {
        asin: "B0CV4V22XL",
        title: "SONGMICS Escritorio Eléctrico Regulable en Altura 160x70 cm",
        note: "Marca consolidada en organización de oficina, tamaño grande para puestos con varios periféricos.",
        img: "https://m.media-amazon.com/images/I/718P+bB13yL._AC_SF480,480_.jpg",
        price: "140",
        rating: "4,4★",
      },
      {
        asin: "B0CHJCB6G1",
        title: "Devoko Escritorio Elevable Eléctrico 160x80 cm con USB-C y Anticolisión",
        note: "Incluye sistema anticolisión y carga USB-C; buen equilibrio de prestaciones en tamaño grande.",
        img: "https://m.media-amazon.com/images/I/51Hy+n--dgL._AC_SF480,480_.jpg",
        price: "159",
        rating: "4,4★",
      },
      {
        asin: "B01N31553J",
        title: "FLEXISPOT E1 Pro Escritorio Elevable Eléctrico, Doble Motor",
        note: "Doble motor de marca especializada en mesas elevables, con 4 funciones de memoria.",
        img: "https://m.media-amazon.com/images/I/61Lo2JtXD4L._AC_SF480,480_.jpg",
        price: "160",
        rating: "4,7★",
      },
      {
        asin: "B0F4JJ8KCV",
        title: "SANODESK Escritorio Elevable Eléctrico con 2 Motores y Anticolisión",
        note: "Doble motor, 4 memorias y anticolisión con la valoración más alta de la selección.",
        img: "https://m.media-amazon.com/images/I/614-3PuNW2L._AC_SF480,480_.jpg",
        price: "190",
        rating: "4,9★",
      },
      {
        asin: "B0DBVFDM3D",
        title: "MAIDeSITe EL2 Pro Art Escritorio Elevable Eléctrico, Doble Motor 180kg",
        note: "Gama alta: doble motor con capacidad de carga de 180 kg y diseño de patas ovaladas.",
        img: "https://m.media-amazon.com/images/I/61yWYUnyA3L._AC_SF480,480_.jpg",
        price: "300",
        rating: "4,8★",
      },
      {
        asin: "B09KNFL1T2",
        title: "FLEXISPOT Escritorio Elevable Eléctrico 160x80, Doble Motor, Tablero Entero",
        note: "El más premium de la selección: tablero de una sola pieza y doble motor para uso intensivo.",
        img: "https://m.media-amazon.com/images/I/71Ge2Etdk0L._AC_SF480,480_.jpg",
        price: "420",
        rating: "4,5★",
      },
    ],
  },
  {
    slug: "auriculares-videollamadas",
    title: "Auriculares para videollamadas: qué mirar además del sonido",
    dek: "Cable o inalámbrico, cancelación de ruido del micrófono y por qué la comodidad importa tanto como el audio.",
    updated: "2026-09-16",
    img: "/assets/img/guias/auriculares-videollamadas.jpg",
    intro: [
      "Para videollamadas, lo que más se nota no es la calidad musical del auricular sino cómo te oyen al otro lado: un micrófono con buena cancelación de ruido de fondo marca más diferencia que unos graves potentes.",
      "Esta guía se centra en los criterios propios del teletrabajo (comodidad en sesiones largas, micrófono, conexión) y no en las prestaciones típicas de auriculares para música o juego.",
    ],
    sections: [
      {
        heading: "Cable, USB o Bluetooth",
        body: [
          "Los auriculares con cable (jack 3.5mm o USB) son los más fiables: cero latencia, cero pilas que se agoten a mitad de una reunión. Es la opción más razonable si trabajas siempre desde el mismo sitio.",
          "El Bluetooth con dongle USB dedicado (no Bluetooth genérico del ordenador) da más libertad de movimiento y suele tener mejor estabilidad de conexión que el Bluetooth integrado. Compensa si te mueves por la habitación durante las llamadas o alternas entre varios dispositivos.",
        ],
      },
      {
        heading: "Cancelación de ruido: en el micrófono, no solo en el oído",
        body: [
          "Muchos auriculares anuncian cancelación de ruido activa (ANC) pensada para que tú no oigas ruido exterior, pero para videollamadas importa igual o más la cancelación de ruido del micrófono (ENC), que filtra el ruido de fondo que llega a la otra persona.",
          "Si trabajas en un espacio compartido o con ruido de fondo (electrodomésticos, calle, otras personas), prioriza modelos que mencionen específicamente reducción de ruido en el micrófono, no solo en los auriculares.",
        ],
      },
      {
        heading: "Comodidad en sesiones largas",
        body: [
          "El peso y la almohadilla de la diadema importan más de lo que parece si vas a llevarlos puestos varias horas seguidas de reuniones. Los modelos on-ear (que se apoyan sobre la oreja) suelen pesar menos pero cansan antes que los over-ear (que rodean la oreja) en sesiones muy largas.",
          "Un micrófono con brazo flexible o abatible permite ajustarlo lejos de la boca cuando no lo necesitas, sin tener que quitarte los auriculares.",
        ],
      },
    ],
    checklist: [
      "Micrófono con cancelación de ruido de fondo (ENC), no solo ANC para el oído",
      "Cable si priorizas fiabilidad; Bluetooth con dongle USB si necesitas movilidad",
      "Diadema y almohadillas cómodas para sesiones de varias horas",
      "Función de silencio (mute) accesible sin abrir la app de videollamada",
      "Compatibilidad confirmada con Teams, Zoom o la plataforma que uses a diario",
    ],
    faq: [
      {
        q: "¿Necesito auriculares \"para oficina\" o me vale cualquier auricular normal?",
        a: "Un auricular normal con micrófono decente puede servir, pero los pensados para oficina suelen cuidar más la cancelación de ruido del micrófono y la comodidad en sesiones largas, que es justo lo que más se nota en videollamadas diarias.",
      },
      {
        q: "¿El Bluetooth es fiable para videollamadas de trabajo?",
        a: "Con un dongle USB dedicado (no el Bluetooth genérico del portátil) la estabilidad es buena y el retardo apenas se nota en voz. El Bluetooth del propio ordenador, sin dongle, es donde más suelen aparecer cortes o desincronización.",
      },
    ],
    products: [
      {
        asin: "B00ZOZZM4U",
        title: "Logitech H111 Auriculares con Cable",
        note: "Entrada de gama con cable jack: la opción más económica y fiable para empezar.",
        img: "https://m.media-amazon.com/images/I/61TKoWoB7+L._AC_SF480,480_.jpg",
        price: "13",
        rating: "4,3★",
      },
      {
        asin: "B008S1IOCY",
        title: "Logitech H340 Auriculares con Cable USB",
        note: "Conexión USB plug-and-play, sin necesidad de configurar entrada de audio por jack.",
        img: "https://m.media-amazon.com/images/I/618gH2IsDaL._AC_SF480,480_.jpg",
        price: "20",
        rating: "4,2★",
      },
      {
        asin: "B005HWEYN0",
        title: "EPOS PC 3 CHAT Auriculares para Ordenador",
        note: "Doble jack de 3.5mm plug-and-play; marca especializada en audio profesional.",
        img: "https://m.media-amazon.com/images/I/61Hmo8CzT9L._AC_SF480,480_.jpg",
        price: "20",
        rating: "4,3★",
      },
      {
        asin: "B0CXTL8YSL",
        title: "Trust Roha II Auriculares USB con Micrófono, Ligeros On Ear",
        note: "Diseño ligero on-ear para quien prioriza no notar peso en sesiones largas.",
        img: "https://m.media-amazon.com/images/I/61-WGbRHc9L._AC_SF480,480_.jpg",
        price: "19",
        rating: "4,2★",
      },
      {
        asin: "B095JJPHL7",
        title: "EKSA H12 Auriculares con Cable y Supresión de Ruido",
        note: "Cancelación de ruido en el micrófono con cable 3.5mm, pensado para call center y oficina.",
        img: "https://m.media-amazon.com/images/I/61jltC4duSL._AC_SF480,480_.jpg",
        price: "19",
        rating: "4,2★",
      },
      {
        asin: "B0F5BPL6PW",
        title: "Logitech H390 Auriculares con Micrófono con Cancelación de Ruido",
        note: "USB con cancelación de ruido en el micrófono; gama media de una marca de referencia en periféricos.",
        img: "https://m.media-amazon.com/images/I/61gfJ379PDL._AC_SF480,480_.jpg",
        price: "40",
        rating: "4,1★",
      },
      {
        asin: "B0F1DGSZPZ",
        title: "Jabra Evolve 10 Auriculares con Cable y Micrófono USB-A",
        note: "Marca especializada en auriculares de oficina profesionales, opción de entrada de su gama.",
        img: "https://m.media-amazon.com/images/I/51mUm9tdv3L._AC_SF480,480_.jpg",
        price: "35",
        rating: "4,2★",
      },
      {
        asin: "B0DX7C6RC9",
        title: "Jabra Evolve 20 Auriculares Estéreo con Cable USB-C/A",
        note: "Gama media de Jabra, certificados para las principales plataformas de videollamada de empresa.",
        img: "https://m.media-amazon.com/images/I/61RLc+CppeL._AC_SF480,480_.jpg",
        price: "39",
        rating: "4,4★",
      },
      {
        asin: "B0C6FLXL5W",
        title: "Poly Blackwire 3225 Auricular con Cable, Micrófono ENC",
        note: "Certificado para Teams y Zoom, con conexión USB-C, USB-A o jack 3.5mm según lo que necesites.",
        img: "https://m.media-amazon.com/images/I/61Xgt6r4kwL._AC_SF480,480_.jpg",
        price: "50",
        rating: "4,1★",
      },
      {
        asin: "B0D1V41GH1",
        title: "Logitech Zone 300 Auriculares con Micrófono Bluetooth",
        note: "Entrada a Bluetooth de Logitech, sin depender de cable para moverte durante la llamada.",
        img: "https://m.media-amazon.com/images/I/61BXENUz1lL._AC_SF480,480_.jpg",
        price: "60",
        rating: "4,2★",
      },
      {
        asin: "B0FM8DGMM2",
        title: "TECKNET Auriculares Inalámbricos con Dongle USB, 60h de Autonomía",
        note: "Bluetooth con dongle USB dedicado (más estable que el Bluetooth genérico) y batería de larga duración.",
        img: "https://m.media-amazon.com/images/I/619+LhlQrzL._AC_SF480,480_.jpg",
        price: "40",
        rating: "4,4★",
      },
      {
        asin: "B0FHTLM4F1",
        title: "TECKNET Auriculares Inalámbricos con Micrófono IA Anti-Ruido",
        note: "Gama alta de TECKNET: cancelación de ruido por IA y base de carga incluida.",
        img: "https://m.media-amazon.com/images/I/71LB2MyQKsL._AC_SF480,480_.jpg",
        price: "43",
        rating: "4,4★",
      },
      {
        asin: "B0BWY4ZZW9",
        title: "EKSA H16 Auriculares Bluetooth con Dongle USB, 55h de Reproducción",
        note: "Alternativa inalámbrica con micrófono con IA anti-ruido, pensada para uso comercial diario.",
        img: "https://m.media-amazon.com/images/I/61zDj3MuJUL._AC_SF480,480_.jpg",
        price: "50",
        rating: "3,9★",
      },
      {
        asin: "B0GPDGFK35",
        title: "Belkin SoundForm Adapt Auriculares Inalámbricos con Micrófono",
        note: "Marca reconocida en accesorios, diseño circumaural inalámbrico para sesiones largas.",
        img: "https://m.media-amazon.com/images/I/71dL7C4cnML._AC_SF480,480_.jpg",
        price: "35",
        rating: "4,3★",
      },
    ],
  },
];

const ARTICLES = [
  {
    slug: "como-montar-tu-escritorio-de-teletrabajo",
    title: "Cómo montar un escritorio de teletrabajo desde cero",
    dek: "El orden en el que conviene decidir cada pieza, y por qué empezar por la silla y no por el monitor.",
    updated: "2026-09-16",
    img: "/assets/img/blog/como-montar-tu-escritorio-de-teletrabajo.jpg",
    body: [
      "Cuando se monta un escritorio de teletrabajo desde cero, es fácil empezar por lo más vistoso (el monitor, la mesa bonita) y dejar para el final lo que más impacto tiene en el cuerpo a largo plazo: la silla y la altura de trabajo.",
      "El orden que mejor funciona es este: primero la silla, porque define la altura de tus ojos y tus brazos respecto a la mesa; después la mesa y su altura (fija o eléctrica); después el monitor y su soporte, ajustado a la altura de tus ojos con la silla ya puesta; y por último teclado, ratón e iluminación, que son ajustes finos sobre una base ya correcta.",
      "Si inviertes el orden —comprando primero un monitor grande y bonito y ajustando la silla después a lo que queda— es muy fácil acabar con el cuello inclinado hacia arriba o hacia abajo, porque la altura del monitor debería depender de dónde quedan tus ojos sentado, no al revés.",
      "Un truco simple para comprobar la altura correcta sin instrumentos: sentado con los pies apoyados y las rodillas a 90°, el borde superior del monitor debe quedar a la altura de tus ojos o ligeramente por debajo. Si tienes que levantar la barbilla para ver la parte de arriba de la pantalla, el monitor está demasiado bajo.",
      "En las guías de este sitio (silla, monitor, teclado y ratón, iluminación) desarrollamos cada pieza por separado con más detalle.",
    ],
  },
  {
    slug: "errores-comunes-ergonomia-oficina",
    title: "5 errores de ergonomía que se repiten en casi todos los escritorios",
    dek: "Cosas fáciles de arreglar que no cuestan dinero, antes de pensar en comprar nada nuevo.",
    updated: "2026-09-11",
    img: "/assets/img/blog/errores-comunes-ergonomia-oficina.jpg",
    body: [
      "Antes de gastar en accesorios nuevos, merece la pena revisar si el problema es de postura y no de equipo: varios de los errores más comunes se arreglan sin comprar nada.",
      "1. Monitor demasiado bajo o demasiado alto. Es el más habitual cuando se trabaja con un portátil sin soporte: la pantalla queda mucho más baja de lo que le conviene al cuello. Un soporte de portátil o, en su defecto, una pila estable de libros, ya corrige buena parte del problema.",
      "2. Sentarse en el borde de la silla sin usar el respaldo. Suele pasar cuando el asiento es demasiado profundo para la estatura de la persona. Si no puedes apoyar la espalda baja en el respaldo sin que las rodillas queden incómodas, el asiento no está bien regulado (o la silla no encaja con tu estatura).",
      "3. Muñecas dobladas hacia arriba al teclear. Pasa cuando el teclado está más alto que los codos. La solución no siempre es un teclado nuevo: a veces basta con bajar la altura de la mesa o de la silla, o usar un reposamuñecas.",
      "4. Ratón demasiado lejos del cuerpo. Si el ratón está fuera del ancho del teclado, obliga a estirar el hombro en cada movimiento. Acercarlo, aunque parezca un detalle menor, reduce mucho la tensión acumulada en sesiones largas.",
      "5. Cero pausas de pie. Ninguna silla, por buena que sea, sustituye a levantarse. Alternar unos minutos de pie cada hora reduce más la fatiga que casi cualquier mejora de equipo.",
    ],
  },
  {
    slug: "cuanto-gastar-en-una-silla-de-oficina",
    title: "¿Cuánto merece la pena gastar en una silla de oficina?",
    dek: "Dónde están los saltos de calidad reales y dónde el precio ya no compra nada nuevo.",
    updated: "2026-09-09",
    img: "/assets/img/blog/cuanto-gastar-en-una-silla-de-oficina.jpg",
    body: [
      "No hay una cifra única válida para todo el mundo, pero sí hay tramos de precio donde el salto de calidad es real y tramos donde ya no se nota tanto.",
      "El primer salto importante está entre una silla sin ninguna regulación (solo altura del gas) y una con las regulaciones básicas: altura, profundidad de asiento, reposabrazos e inclinación bloqueable. Ese salto es el que más impacto tiene en la postura, independientemente de la marca.",
      "El segundo salto, más caro, está en materiales y durabilidad: mecanismos más suaves, mallas o tapizados que aguantan mejor el paso de los años, garantías más largas y piezas de recambio disponibles (ruedas, pistón de gas, reposabrazos). Este tramo compensa sobre todo si vas a usar la silla muchas horas al día durante años.",
      "A partir de cierto precio, lo que se paga de más suele ser diseño, marca o acabados, no ergonomía adicional: las regulaciones que de verdad importan (ver la guía de sillas ergonómicas) ya estaban presentes en el tramo anterior.",
      "La pregunta que más ayuda a decidir no es \"¿cuánto cuesta?\" sino \"¿cuántas horas al día la voy a usar?\". A más horas de uso diario, más se justifica invertir en el tramo de regulaciones completas y buena durabilidad.",
    ],
  },
  {
    slug: "ilumina-tu-escritorio-sin-deslumbrar",
    title: "Ilumina tu escritorio sin deslumbrarte en las videollamadas",
    dek: "Cómo colocar la luz para que se vea bien en cámara sin que moleste a la vista al trabajar.",
    updated: "2026-09-08",
    img: "/assets/img/blog/ilumina-tu-escritorio-sin-deslumbrar.jpg",
    body: [
      "La luz que hace que se te vea bien en una videollamada y la luz que necesitas para trabajar cómodo no siempre son la misma, y ajustarlas a la vez es más sencillo de lo que parece.",
      "Para cámara, la luz debe venir de frente o ligeramente de lado, nunca solo desde atrás (a contraluz te vuelves una silueta) ni solo desde arriba (genera sombras duras bajo los ojos). Una fuente de luz suave situada detrás de la pantalla, apuntando hacia tu cara, suele bastar sin necesidad de un aro de luz dedicado.",
      "Para trabajar, esa misma luz frontal no debe deslumbrarte a ti: si la fuente está muy cerca de tu línea de visión y muy brillante, cansa la vista en sesiones largas. La solución habitual es una luz de intensidad regulable, baja para trabajar y algo más alta justo antes de una videollamada.",
      "Evita colocar cualquier lámpara justo detrás del monitor mirando hacia ti: además de deslumbrar, suele generar un reflejo visible en la pantalla que se nota tanto trabajando como en cámara.",
    ],
  },
];

// Un producto destacado por categoría, para el bloque "Lo más recomendado"
// que aparece en todas las páginas (ver featuredProductsSection en lib.js).
// Se reutilizan los datos ya cargados en GUIDES para no duplicar imagen/precio.
function pickFeatured(guideSlug, asin) {
  const g = GUIDES.find((x) => x.slug === guideSlug);
  const p = g.products.find((x) => x.asin === asin);
  return { ...p, category: g.slug, categoryTitle: g.title };
}

const FEATURED = [
  pickFeatured("sillas-ergonomicas", "B0GWRDPZZF"),
  pickFeatured("monitores", "B0GW8PLMZM"),
  pickFeatured("teclados-y-raton", "B07W6J71BL"),
  pickFeatured("iluminacion-escritorio", "B0GGXPFW9X"),
  pickFeatured("organizacion-cables-y-espacio", "B0GT8V2JVZ"),
];

module.exports = { GUIDES, ARTICLES, FEATURED };
